In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv(r"C:\Data Sets\winequality_red.csv")

In [3]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [4]:
data.shape

(1599, 12)

In [5]:
inp_data=data.drop('quality',axis=1)

In [8]:
from sklearn.decomposition import PCA

pca=PCA(n_components=4)
pca.fit(inp_data)

PCA(n_components=4)

In [9]:
data_pca=pca.transform(inp_data)

In [10]:
data_pca

array([[-13.22490501,  -2.02389981,  -1.12682053,  -0.39923318],
       [ 22.03772361,   4.40832155,  -0.31037799,  -0.19993774],
       [  7.16267333,  -2.50146086,  -0.5818683 ,  -0.21906928],
       ...,
       [ -3.43135351,  14.27124349,  -1.75071927,   0.17465219],
       [  1.13287834,  16.31616732,  -2.13441396,  -0.23538796],
       [ -3.8743766 ,   3.12634754,  -1.87414925,   1.7006739 ]])

In [14]:
pca.transform(inp_data)

array([[-13.22490501,  -2.02389981,  -1.12682053,  -0.39923318],
       [ 22.03772361,   4.40832155,  -0.31037799,  -0.19993774],
       [  7.16267333,  -2.50146086,  -0.5818683 ,  -0.21906928],
       ...,
       [ -3.43135351,  14.27124349,  -1.75071927,   0.17465219],
       [  1.13287834,  16.31616732,  -2.13441396,  -0.23538796],
       [ -3.8743766 ,   3.12634754,  -1.87414925,   1.7006739 ]])

In [16]:
pca.explained_variance_ratio_

array([0.94657698, 0.0483683 , 0.00258917, 0.00151897])

In [18]:
pca.explained_variance_

array([1133.80707551,   57.93541077,    3.10130228,    1.81941532])