$ Feture-Selection $

# Retrival the important deatures,selecting an important fetures in vaey important step before going to ML

- Droping the constant fetures(regression and Classinication)

- Information gain(Classification)

- p-value(Regression)

- VIF(Regression)

- Forward selection and backwoard selection(Regression classification)

- Correleation with target column(Regression classification)


Feature selection methods

1.Variance threshold:
  - Based on variance we can decide the data is constant or varing

  - Data is not varying we can decide the data is constant or varying

  - Data is not varting much means,data has same values

  - For example we have seen in loan dataset,loan term:360

  - Python by default will use va

## $Method-1 $ : Variance threshold method

- Droping constanat fetures

- Variance indiacates how data distribution happens

- Constant fetures have less variance

- by keeping some thrashold we can remove those features

- The feture values  through out the data iis the same

- you can decide manually what is your desired variance in order to keep the feture

In [1]:
import pandas as pd
dict1={'A':[100,200,300,400],
      'B':[1,2,3,4],
      'C':[10,20,30,40],
      'D':[10,10,10,10]}
df=pd.DataFrame(dict1)
df

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [15]:
from sklearn.feature_selection import VarianceThreshold

# Initialize the VarianceThreshold instance with a threshold of 0
vt = VarianceThreshold(threshold=0)

# Fit the model to the data (assuming df is your DataFrame)
vt.fit(df)



VarianceThreshold(threshold=0)

In [16]:
dir(vt)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'feature_names_in_',
 'fit',
 'fit_tran

In [17]:
vt.feature_names_in_

array(['A', 'B', 'C', 'D'], dtype=object)

In [19]:
vt.get_feature_names_out()

array(['A', 'B', 'C'], dtype=object)

In [21]:
vt.get_params()

{'threshold': 0}

In [23]:
vt.get_support() #true=in false=out

array([ True,  True,  True, False])

In [24]:
vt.threshold

0

In [28]:
vt.variances_

array([300.  ,   1.25,  30.  ,   0.  ])

In [29]:
new_df=df[vt.get_feature_names_out()]

In [30]:
new_df

A  B   C
0  100  1  10
1  200  2  20
2  300  3  30
3  400  4  40

In [32]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [33]:
#Step-1:Read wine quality data

In [36]:
data=pd.read_csv(r"C:\Data Sets\winequality_red.csv")
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [35]:
data.shape

(1599, 12)

In [39]:
inp_data=data.drop('quality',axis=1)

In [40]:
vt.fit(inp_data)

VarianceThreshold(threshold=0)

In [41]:
vt.feature_names_in_

array(['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol'],
      dtype=object)

In [43]:
vt.get_feature_names_out()

array(['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol'],
      dtype=object)

In [45]:
vt.get_params()

{'threshold': 0}

In [46]:
vt.variances_

array([3.02952057e+00, 3.20423261e-02, 3.79237511e-02, 1.98665392e+00,
       2.21375732e-03, 7.10000000e+01, 2.83000000e+02, 3.55980179e-06,
       2.38202742e-02, 2.87146470e-02, 1.13493717e+00])

In [48]:
new_df=inp_data[vt.get_feature_names_out()]

In [54]:
print(new_df)
print(new_df.shape)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

In [50]:
vt.threshold=1

In [51]:
vt.get_feature_names_out()

array(['fixed acidity', 'residual sugar', 'free sulfur dioxide',
       'total sulfur dioxide', 'alcohol'], dtype=object)

In [55]:
trah1=inp_data[vt.get_feature_names_out()]

In [57]:
trah1.shape

(1599, 5)

In [58]:
vt.trashold=2

In [59]:
vt.get_feature_names_out()


array(['fixed acidity', 'residual sugar', 'free sulfur dioxide',
       'total sulfur dioxide', 'alcohol'], dtype=object)

In [60]:
vt.trashold=3

In [61]:
vt.get_feature_names_out()

array(['fixed acidity', 'residual sugar', 'free sulfur dioxide',
       'total sulfur dioxide', 'alcohol'], dtype=object)

In [62]:
vt.variances_

array([3.02952057e+00, 3.20423261e-02, 3.79237511e-02, 1.98665392e+00,
       2.21375732e-03, 7.10000000e+01, 2.83000000e+02, 3.55980179e-06,
       2.38202742e-02, 2.87146470e-02, 1.13493717e+00])

In [63]:
vt.threshold=1.5

In [64]:
vt.get_feature_names_out()

array(['fixed acidity', 'residual sugar', 'free sulfur dioxide',
       'total sulfur dioxide'], dtype=object)

## Information gain

mutual info classify

- It is a valu estimating how much relationship/how much information about target variable

- we dont want relation between input features

- we want relation between input and output feture

- 0 means both variables are indepenent

- Here will use entropy or KNN method based on joint probability

- Mutual info classift will take input columns data and output colummns data

- wright it leter

In [65]:
data=pd.read_csv(r"C:\Data Sets\winequality_red.csv")
x=data.drop('quality',axis=1) 
y=data['quality']

In [66]:
len(data.columns),len(x.columns)

(12, 11)

In [68]:
x.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [70]:
from sklearn.feature_selection import mutual_info_classif
MI=mutual_info_classif(x,y)
MI

array([0.03691758, 0.12872664, 0.07932155, 0.00905628, 0.02515342,
       0.03472066, 0.08913456, 0.08377221, 0.03432048, 0.10310941,
       0.16462623])

In [73]:
d=pd.DataFrame(MI,index=x.columns,
              columns=['MI'])

In [74]:
d

MI
fixed acidity         0.036918
volatile acidity      0.128727
citric acid           0.079322
residual sugar        0.009056
chlorides             0.025153
free sulfur dioxide   0.034721
total sulfur dioxide  0.089135
density               0.083772
pH                    0.034320
sulphates             0.103109
alcohol               0.164626

In [75]:
sorted_data=d.sort_values(by="MI",ascending=False)
sorted_data

MI
alcohol               0.164626
volatile acidity      0.128727
sulphates             0.103109
total sulfur dioxide  0.089135
density               0.083772
citric acid           0.079322
fixed acidity         0.036918
free sulfur dioxide   0.034721
pH                    0.034320
chlorides             0.025153
residual sugar        0.009056

In [77]:
con=sorted_data['MI']>0.10
cols=sorted_data['MI']>0.0792

In [78]:
con

alcohol                  True
volatile acidity         True
sulphates                True
total sulfur dioxide    False
density                 False
citric acid             False
fixed acidity           False
free sulfur dioxide     False
pH                      False
chlorides               False
residual sugar          False
Name: MI, dtype: bool

## How to get Top 5 Columns Manually

In [81]:
d=pd.DataFrame(MI,columns=['Information gain'],
              index=x.columns)
sorted_d=d.sort_values('Information gain',ascending=False)
data[sorted_d.index[:5]]

alcohol  volatile acidity  sulphates  total sulfur dioxide  density
0         9.4             0.700       0.56                  34.0  0.99780
1         9.8             0.880       0.68                  67.0  0.99680
2         9.8             0.760       0.65                  54.0  0.99700
3         9.8             0.280       0.58                  60.0  0.99800
4         9.4             0.700       0.56                  34.0  0.99780
...       ...               ...        ...                   ...      ...
1594     10.5             0.600       0.58                  44.0  0.99490
1595     11.2             0.550       0.76                  51.0  0.99512
1596     11.0             0.510       0.75                  40.0  0.99574
1597     10.2             0.645       0.71                  44.0  0.99547
1598     11.0             0.310       0.66                  42.0  0.99549

[1599 rows x 5 columns]

In [82]:
d

Information gain
fixed acidity                 0.036918
volatile acidity              0.128727
citric acid                   0.079322
residual sugar                0.009056
chlorides                     0.025153
free sulfur dioxide           0.034721
total sulfur dioxide          0.089135
density                       0.083772
pH                            0.034320
sulphates                     0.103109
alcohol                       0.164626